### ISSUE TITLE
Ghost 2.0

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/ghost-jsdelivr-theme#1]
![ghost](https://user-images.githubusercontent.com/1834071/56977182-e55d8300-6b74-11e9-9f58-a50b4ff8505f.png)

@MartinKolarik Can your team organize an upgrade of our theme to work on new Ghost?

**Comment by MartinKolarik** [comment]
@Drgy since this is a new major version of Ghost, the readme instructions here might be outdated as well. Please consult the official docs.

**Comment by jimaek** [comment]
Also need to fix the URLs here https://dl.dropboxusercontent.com/s/yowil63aws3tazk/chrome_CwL8JONxiu.png

**Comment by MartinKolarik** [comment]
@jimaek not sure where you found those errors but please check now.
