### ISSUE TITLE
Ghost 5 template updates

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/ghost-jsdelivr-theme#10]
Ghost insists to upgrade us to v5

1. Test locally to ensure our theme works with latest Ghost
2. Send PR with fixes if needed

**Comment by jimaek** [comment]
@ayuhito is this something you would be able to look into?

**Comment by ayuhito** [comment]
@jimaek, sure thing. Feel free to assign to me.

**Comment by jimaek** [comment]
If you do not upgrade before January 31st, we will automatically upgrade the site for you, and your theme may require changes for compatibility. We’ll display any required changes your theme may need in a red notification window within Ghost Admin.

**Comment by ayuhito** [comment]
I'll check on this today then ^^
